#!/bin/bash

# Arte ASCII
ascii_art="
 _   _ _____ ____   ___  _   _ ___ _  __
| \ | | ____/ ___| / _ \| | | |_ _| |/ /
|  \| |  _| \___ \| | | | | | || || ' / 
| |\  | |___ ___) | |_| | |_| || || . \ 
|_| \_|_____|____/ \__\_\\___/|___|_|\_\
"

# Cores
VERMELHO='\033[0;31m'
VERDE='\033[0;32m'
AZUL='\033[0;34m'
CIANO='\033[0;36m'
AMARELO='\033[0;33m'
SEM_COR='\033[0m' # Sem cor

# Limpa a tela
clear

# Verifica se o script está sendo executado como root
if [ "$EUID" -ne 0 ]; then
  echo -e "${VERMELHO}Por favor, execute este script como root.${SEM_COR}"
  exit 1
fi

echo -e "${CIANO}$ascii_art${SEM_COR}"

echo "* Instalando dependências"

# Atualiza a lista de pacotes e instala dependências
sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo "* Dependências instaladas"

echo "* Instalando arquivos"

# Cria diretório, clona o repositório e instala arquivos
mkdir -p panel5
cd panel5 || { echo "Falha ao mudar para o diretório panel5"; exit 1; }
git clone https://github.com/achul123/panel5.git
cd panel5 || { echo "Falha ao mudar para o diretório panel5"; exit 1; }
npm install

echo "* Arquivos instalados"

echo "* Iniciando Skyport"

# Executa os scripts de configuração
npm run seed
npm run createUser

echo "* Iniciando Skyport com PM2"

# Instala o PM2 e inicia a aplicação
sudo npm install -g pm2
pm2 start index.js

echo "* Skyport instalado e iniciado na porta 3001"

# Limpa a tela após finalizar
clear
echo "* Feito por NesquikDeveloper"
